[2021-10-12 13:35:15,161] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: estate_pipeline.data_reader 2021-10-12T05:32:16.548248+00:00 [queued]>
[2021-10-12 13:35:15,168] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: estate_pipeline.data_reader 2021-10-12T05:32:16.548248+00:00 [queued]>
[2021-10-12 13:35:15,168] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-12 13:35:15,168] {taskinstance.py:1096} INFO - Starting attempt 1 of 3
[2021-10-12 13:35:15,168] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-12 13:35:15,175] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data_reader> on 2021-10-12T05:32:16.548248+00:00
[2021-10-12 13:35:15,178] {standard_task_runner.py:52} INFO - Started process 17480 to run task
[2021-10-12 13:35:15,182] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'estate_pipeline', 'data_reader', '2021-10-12T05:32:16.548248+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpiswrqfo2', '--error-file', '/tmp/tmpj3tt3sda']
[2021-10-12 13:35:15,186] {standard_task_runner.py:77} INFO - Job 3: Subtask data_reader
[2021-10-12 13:35:15,211] {logging_mixin.py:109} INFO - Running <TaskInstance: estate_pipeline.data_reader 2021-10-12T05:32:16.548248+00:00 [running]> on host ubuntu
[2021-10-12 13:35:15,236] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=swchen1282@gmail.com
AIRFLOW_CTX_DAG_OWNER=swc
AIRFLOW_CTX_DAG_ID=estate_pipeline
AIRFLOW_CTX_TASK_ID=data_reader
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T05:32:16.548248+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-12T05:32:16.548248+00:00
[2021-10-12 13:35:15,238] {logging_mixin.py:109} INFO - absolute_path=/home/dev/cbkpi/app/airflow_root/dags
[2021-10-12 13:35:15,238] {logging_mixin.py:109} INFO - data_source_path=/home/dev/cbkpi/app
[2021-10-12 13:35:15,238] {logging_mixin.py:109} INFO - ['107S4.zip', '108S2.zip', '108S3.zip', '107S1', '107S1.zip', '109S1', '106S1', '108S4.zip', '108S4', '107S2', '107S2.zip', '106S2.zip', '108S3', '109S2', '109S4.zip', '106S2', '107S4', '106S3', '108S1', '109S2.zip', '106S3.zip', '106S4.zip', '109S3', '109S4', '109S1.zip', '106S4', '107S3', '108S1.zip', '106S1.zip', '107S3.zip', '108S2', '109S3.zip']
[2021-10-12 13:35:15,238] {logging_mixin.py:109} INFO - current path is: /home/dev/cbkpi/app/data_source; start data processing
[2021-10-12 13:35:15,240] {logging_mixin.py:109} INFO - 107S4.zip is a zip file, skip
[2021-10-12 13:35:15,240] {logging_mixin.py:109} INFO - 108S2.zip is a zip file, skip
[2021-10-12 13:35:15,240] {logging_mixin.py:109} INFO - 108S3.zip is a zip file, skip
[2021-10-12 13:35:15,268] {logging_mixin.py:109} INFO - import 107_1_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:15,385] {logging_mixin.py:109} INFO - import 107_1_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:15,409] {logging_mixin.py:109} INFO - import 107_1_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:15,488] {logging_mixin.py:109} INFO - import 107_1_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:15,559] {logging_mixin.py:109} INFO - import 107_1_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:15,559] {logging_mixin.py:109} INFO - 107S1.zip is a zip file, skip
[2021-10-12 13:35:15,587] {logging_mixin.py:109} INFO - import 109_1_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:15,727] {logging_mixin.py:109} INFO - import 109_1_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:15,764] {logging_mixin.py:109} INFO - import 109_1_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:15,859] {logging_mixin.py:109} INFO - import 109_1_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:15,957] {logging_mixin.py:109} INFO - import 109_1_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:15,994] {logging_mixin.py:109} INFO - import 106_1_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:16,128] {logging_mixin.py:109} INFO - import 106_1_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:16,175] {logging_mixin.py:109} INFO - import 106_1_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:16,268] {logging_mixin.py:109} INFO - import 106_1_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:16,361] {logging_mixin.py:109} INFO - import 106_1_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:16,362] {logging_mixin.py:109} INFO - 108S4.zip is a zip file, skip
[2021-10-12 13:35:16,408] {logging_mixin.py:109} INFO - import 108_4_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:16,589] {logging_mixin.py:109} INFO - import 108_4_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:16,658] {logging_mixin.py:109} INFO - import 108_4_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:16,767] {logging_mixin.py:109} INFO - import 108_4_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:16,895] {logging_mixin.py:109} INFO - import 108_4_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:16,986] {logging_mixin.py:109} INFO - import 107_2_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:17,162] {logging_mixin.py:109} INFO - import 107_2_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:17,279] {logging_mixin.py:109} INFO - import 107_2_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:17,433] {logging_mixin.py:109} INFO - import 107_2_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:17,636] {logging_mixin.py:109} INFO - import 107_2_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:17,636] {logging_mixin.py:109} INFO - 107S2.zip is a zip file, skip
[2021-10-12 13:35:17,636] {logging_mixin.py:109} INFO - 106S2.zip is a zip file, skip
[2021-10-12 13:35:17,755] {logging_mixin.py:109} INFO - import 108_3_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:18,054] {logging_mixin.py:109} INFO - import 108_3_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:18,225] {logging_mixin.py:109} INFO - import 108_3_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:18,472] {logging_mixin.py:109} INFO - import 108_3_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:18,692] {logging_mixin.py:109} INFO - import 108_3_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:18,883] {logging_mixin.py:109} INFO - import 109_2_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:19,070] {logging_mixin.py:109} INFO - import 109_2_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:19,280] {logging_mixin.py:109} INFO - import 109_2_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:19,456] {logging_mixin.py:109} INFO - import 109_2_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:19,777] {logging_mixin.py:109} INFO - import 109_2_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:19,777] {logging_mixin.py:109} INFO - 109S4.zip is a zip file, skip
[2021-10-12 13:35:20,205] {logging_mixin.py:109} INFO - import 106_2_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:20,584] {logging_mixin.py:109} INFO - import 106_2_H_B data into pd.DataFrame successfully
[2021-10-12 13:35:20,783] {logging_mixin.py:109} INFO - import 106_2_E_A data into pd.DataFrame successfully
[2021-10-12 13:35:21,103] {logging_mixin.py:109} INFO - import 106_2_A_A data into pd.DataFrame successfully
[2021-10-12 13:35:21,329] {logging_mixin.py:109} INFO - import 107_4_B_B data into pd.DataFrame successfully
[2021-10-12 13:35:21,606] {logging_mixin.py:109} INFO - import 107_4_F_A data into pd.DataFrame successfully
[2021-10-12 13:35:21,748] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 17480
[2021-10-12 13:35:21,764] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-10-12 13:35:21,768] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dev/cbkpi/app/airflow_root/dags/data_reader.py", line 32, in data_reader
    result = result.append(data)
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 7751, in append
    sort=sort,
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 362, in __init__
    obj._consolidate(inplace=True)
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5234, in _consolidate
    self._consolidate_inplace()
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5216, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5205, in _protect_consolidate
    result = f()
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5214, in f
    self._mgr = self._mgr.consolidate()
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 983, in consolidate
    bm._consolidate_inplace()
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 988, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1909, in _consolidate
    list(group_blocks), dtype=dtype, can_consolidate=_can_consolidate
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1934, in _merge_blocks
    new_values = new_values[argsort]
  File "/home/dev/cbkpi/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-10-12 13:35:21,783] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=estate_pipeline, task_id=data_reader, execution_date=20211012T053216, start_date=20211012T053515, end_date=20211012T053521
[2021-10-12 13:35:21,809] {process_utils.py:66} INFO - Process psutil.Process(pid=17480, status='terminated', exitcode=1, started='13:35:14') (17480) terminated with exit code 1
